1. Test whether is tensor

In [2]:
import torch
x=[12,23,34,45,56,67,78]
print(torch.is_tensor(x))
print(torch.is_storage(x))

False
False


2. Create tensor

In [3]:
y=torch.randn(1,2,3,4,5)
print(y)
print(torch.is_tensor(y))
print(torch.is_storage(y))
print(torch.numel(y)) # the total number

y=torch.zeros(4,4)
print(y)
print(torch.numel(y))

import numpy as np
x=[12,23,34,45,56,67,78]
x1=np.array(x)
x2=torch.from_numpy(x1)
print(x,x1,x2)



tensor([[[[[-1.2654, -0.4721,  1.1072,  0.2130,  0.8361],
           [ 0.9269,  0.2851, -0.9700, -0.4201, -0.8867],
           [ 1.1652,  0.9376, -0.2131, -1.1889, -2.3763],
           [-0.4137,  1.8714,  0.0876,  0.5302, -0.4463]],

          [[ 1.1039, -0.3791,  0.3027, -1.3806, -1.7241],
           [-0.9098,  1.6286,  0.8450, -1.7519,  1.5009],
           [-0.6160,  1.6669,  0.7432,  0.3975, -0.6836],
           [ 0.0742, -0.3340, -0.3726,  0.0649, -0.2856]],

          [[ 2.3503,  0.1088, -0.9470, -0.1984, -1.8084],
           [-1.2942,  0.0813,  0.4506, -0.6650,  0.4043],
           [-0.5098, -0.3679, -0.4945,  0.6992,  0.4490],
           [ 0.5258, -0.6801, -0.2234,  0.6027, -0.3002]]],


         [[[ 0.7118, -0.3196, -0.6672, -0.1828, -0.6974],
           [-0.5868,  0.3881, -0.6683,  2.6885, -1.6799],
           [ 0.5150, -0.6756, -0.7882,  0.3266, -0.0670],
           [ 1.2276, -1.1861, -0.3233, -1.3147,  0.5690]],

          [[ 0.5498,  0.3118,  0.8136,  0.6714,  0.7296],
    

3. eye function

In [4]:
print(torch.eye(3,4))
print(torch.eye(5,4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])


4. linspace, logspace and rand

In [5]:
torch.linspace(2,10,steps=25)
torch.logspace(2,10,steps=25)

print(torch.rand(10))
print(torch.rand(4,5))
print(torch.randn(10)) # norm distribution
print(torch.randn(4,5))

print(torch.randperm(10))
print(torch.arange(10,40,2))
print(torch.arange(10,40))


tensor([0.1475, 0.0832, 0.2579, 0.7016, 0.4955, 0.1888, 0.1309, 0.9362, 0.7393,
        0.8996])
tensor([[0.6125, 0.1642, 0.8989, 0.8973, 0.5606],
        [0.5055, 0.3278, 0.6129, 0.5192, 0.7917],
        [0.6251, 0.0811, 0.5359, 0.7546, 0.5378],
        [0.5100, 0.4415, 0.9887, 0.3905, 0.9440]])
tensor([-1.5719, -0.0370,  0.3833, -0.5003,  1.0095,  0.7698, -2.8843, -0.2460,
        -0.2279,  1.0365])
tensor([[-0.5849,  0.0336,  0.4904,  0.3730, -1.2626],
        [-0.4145,  0.2245, -0.1639, -1.1544, -0.4357],
        [-0.3700,  2.0400,  0.2840,  2.1190,  1.7938],
        [ 0.5312,  0.0821, -1.2625,  0.0702,  1.5055]])
tensor([7, 2, 6, 9, 8, 1, 4, 5, 3, 0])
tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])


5. find the max and min

In [6]:
d=torch.randn(4,5)
print(d)
print(torch.argmin(d,dim=0)) # min in every row
print(torch.argmin(d,dim=1)) # min in every col

tensor([[ 9.1929e-02,  1.1974e+00,  1.1255e+00,  1.3076e-01,  8.7929e-02],
        [ 8.7010e-01, -6.5486e-01, -6.5962e-01,  2.9421e-01,  8.9274e-04],
        [-1.6919e-01, -5.9439e-01,  6.9426e-01,  2.4483e+00, -1.5632e-01],
        [ 1.0267e-01,  3.6455e-01, -5.1265e-01, -3.5043e-01,  1.7062e-01]])
tensor([2, 1, 1, 3, 2])
tensor([4, 2, 1, 2])


6. concatenation and chunk and split(for 1D tensor)

In [7]:
x=torch.randn(4,5)
print(x)
print(torch.cat((x,x))) # cat by row
print(torch.cat((x,x),0)) # cat by row
print(torch.cat((x,x),1)) # cat by col

x=torch.randn(4,4)
print(x)
print(torch.chunk(x,2))   # split along row
print(torch.chunk(x,2,0)) # split along row
print(torch.chunk(x,2,1)) # split along col

print(torch.split(torch.tensor([12,23,34,45,56,67]),2))

tensor([[ 2.4894,  1.2911,  2.0792, -0.2889,  1.9409],
        [-0.5101, -1.1040,  0.0980,  0.3185,  0.4110],
        [ 0.3023, -1.3319,  0.5232,  0.4051, -0.1482],
        [ 0.7075, -2.4303, -0.0303,  2.2324,  0.9351]])
tensor([[ 2.4894,  1.2911,  2.0792, -0.2889,  1.9409],
        [-0.5101, -1.1040,  0.0980,  0.3185,  0.4110],
        [ 0.3023, -1.3319,  0.5232,  0.4051, -0.1482],
        [ 0.7075, -2.4303, -0.0303,  2.2324,  0.9351],
        [ 2.4894,  1.2911,  2.0792, -0.2889,  1.9409],
        [-0.5101, -1.1040,  0.0980,  0.3185,  0.4110],
        [ 0.3023, -1.3319,  0.5232,  0.4051, -0.1482],
        [ 0.7075, -2.4303, -0.0303,  2.2324,  0.9351]])
tensor([[ 2.4894,  1.2911,  2.0792, -0.2889,  1.9409],
        [-0.5101, -1.1040,  0.0980,  0.3185,  0.4110],
        [ 0.3023, -1.3319,  0.5232,  0.4051, -0.1482],
        [ 0.7075, -2.4303, -0.0303,  2.2324,  0.9351],
        [ 2.4894,  1.2911,  2.0792, -0.2889,  1.9409],
        [-0.5101, -1.1040,  0.0980,  0.3185,  0.4110],
        

7. gather:  The gather function collects elements from a tensor and places it in
another tensor using an index argument. The index position is determined
by the LongTensor function in PyTorch.
&
select

In [8]:
a=torch.Tensor([[11,12],[23,24]])
b=torch.LongTensor([[0,0],[1,0]])
print(a)
print(b)

print(torch.gather(a,0,b))  # 1: 列保留，选择行
print(torch.gather(a,1,b))  # 1: 行保留，选择列


a=torch.randn(4,4)
print(a)
indices=torch.LongTensor([0,2])
print(indices)
print(torch.index_select(a,0,indices))
print(torch.index_select(a,1,indices))


tensor([[11., 12.],
        [23., 24.]])
tensor([[0, 0],
        [1, 0]])
tensor([[11., 12.],
        [23., 12.]])
tensor([[11., 11.],
        [24., 23.]])
tensor([[-0.4981, -1.5770, -1.4701,  1.6725],
        [-0.9015,  0.0826,  0.5239, -0.6269],
        [ 0.5324, -0.6548, -0.2198,  0.7140],
        [ 0.6528,  1.4154, -0.8080,  0.5039]])
tensor([0, 2])
tensor([[-0.4981, -1.5770, -1.4701,  1.6725],
        [ 0.5324, -0.6548, -0.2198,  0.7140]])
tensor([[-0.4981, -1.4701],
        [-0.9015,  0.5239],
        [ 0.5324, -0.2198],
        [ 0.6528, -0.8080]])


8. nonzero

In [9]:
print(torch.nonzero(torch.tensor([10,00,23,0,0.0])))

tensor([[0],
        [2]])


9.change the shape
- transpose
- unbind(remove a dim)

In [10]:
x=torch.rand(4,5)
print(x)
print(x.t()) # only used for 2D

x=torch.rand(4,5,3)
print(x.transpose(0,2)) #for all dims

x=torch.rand(4,5)
print(x)
print(torch.unbind(x,0)) # remove row
print(torch.unbind(x,1)) # remove col


tensor([[0.4185, 0.6557, 0.2603, 0.7732, 0.5345],
        [0.8096, 0.1773, 0.7098, 0.6866, 0.4042],
        [0.2247, 0.4801, 0.6018, 0.8903, 0.0897],
        [0.2031, 0.2024, 0.5996, 0.6098, 0.0264]])
tensor([[0.4185, 0.8096, 0.2247, 0.2031],
        [0.6557, 0.1773, 0.4801, 0.2024],
        [0.2603, 0.7098, 0.6018, 0.5996],
        [0.7732, 0.6866, 0.8903, 0.6098],
        [0.5345, 0.4042, 0.0897, 0.0264]])
tensor([[[0.5607, 0.7881, 0.9401, 0.2481],
         [0.7562, 0.8927, 0.4849, 0.4867],
         [0.6717, 0.8905, 0.7503, 0.2705],
         [0.7513, 0.3668, 0.7827, 0.8228],
         [0.8377, 0.3732, 0.8331, 0.5810]],

        [[0.6009, 0.5166, 0.2526, 0.1518],
         [0.4157, 0.4560, 0.3298, 0.3620],
         [0.2661, 0.4202, 0.4779, 0.0165],
         [0.7572, 0.0977, 0.8163, 0.1661],
         [0.5665, 0.3603, 0.5165, 0.6409]],

        [[0.4456, 0.1507, 0.6961, 0.2956],
         [0.3222, 0.9019, 0.8785, 0.6170],
         [0.5126, 0.5668, 0.0958, 0.1844],
         [0.2592, 0.3199,

10. Scalar,ceil,floor and clamp

In [14]:
x=torch.rand(4,5)
print(torch.add(x,20))
print(torch.mul(x,2))

torch.manual_seed(1234)
x=torch.randn(5,5)
print(x)
print(torch.ceil(x))
print(torch.floor(x))
print(torch.clamp(x,min=-0.3,max=0.4))


tensor([[20.0014, 20.5414, 20.6419, 20.2976, 20.7077],
        [20.4189, 20.0655, 20.8839, 20.8083, 20.7528],
        [20.8988, 20.6839, 20.7658, 20.9149, 20.3993],
        [20.1100, 20.2541, 20.4333, 20.4451, 20.4966]])
tensor([[0.0028, 1.0828, 1.2838, 0.5952, 1.4153],
        [0.8379, 0.1310, 1.7677, 1.6166, 1.5056],
        [1.7977, 1.3677, 1.5317, 1.8298, 0.7985],
        [0.2201, 0.5082, 0.8665, 0.8901, 0.9932]])
tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])
tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])
tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1

11. exp(calculate exp for each element, not the exp of matrix) and get frac portion

In [20]:
x=torch.rand(4,5)
x[0,0]=1
print(torch.exp(x))
print(torch.frac(x))
print(torch.log(x))
print(torch.pow(x,2))
print(torch.sqrt(x))

tensor([[2.7183, 1.4187, 1.4893, 2.0916, 1.0883],
        [1.5288, 2.6586, 1.9738, 1.3704, 1.4786],
        [2.4457, 1.9915, 2.3139, 1.1949, 1.9044],
        [1.8029, 1.7989, 2.6229, 2.1745, 2.3272]])
tensor([[0.0000, 0.3497, 0.3983, 0.7379, 0.0846],
        [0.4245, 0.9778, 0.6800, 0.3151, 0.3911],
        [0.8943, 0.6889, 0.8389, 0.1780, 0.6442],
        [0.5894, 0.5872, 0.9643, 0.7768, 0.8447]])
tensor([[ 0.0000, -1.0506, -0.9206, -0.3039, -2.4696],
        [-0.8569, -0.0224, -0.3857, -1.1548, -0.9388],
        [-0.1117, -0.3727, -0.1756, -1.7258, -0.4398],
        [-0.5287, -0.5325, -0.0364, -0.2526, -0.1688]])
tensor([[1.0000, 0.1223, 0.1586, 0.5445, 0.0072],
        [0.1802, 0.9561, 0.4623, 0.0993, 0.1530],
        [0.7998, 0.4746, 0.7038, 0.0317, 0.4149],
        [0.3474, 0.3448, 0.9298, 0.6034, 0.7134]])
tensor([[1.0000, 0.5914, 0.6311, 0.8590, 0.2909],
        [0.6515, 0.9888, 0.8246, 0.5614, 0.6254],
        [0.9457, 0.8300, 0.9159, 0.4219, 0.8026],
        [0.7677, 0.7663, 0

12. transformation functions: i.e., sigmoid, hyperbolic
tangent, radial basis function, and so forth

In [19]:
x=torch.rand(4,5)
torch.sigmoid(x)


tensor([[0.6599, 0.7268, 0.5259, 0.5968, 0.6476],
        [0.5232, 0.5180, 0.7054, 0.5800, 0.6882],
        [0.6329, 0.6507, 0.5416, 0.5971, 0.6963],
        [0.6747, 0.5879, 0.6368, 0.7074, 0.5155]])